Solucao/TCC.GestaoSaude/TCC.GestaoSaude.View/Models/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TCC.GestaoSaude.Business;
using TCC.GestaoSaude.DataAccess.Interface;
using TCC.GestaoSaude.Models;
using TCC.GestaoSaude.View.SessionCustom;

namespace TCC.GestaoSaude.View.Models.ViewComponents
{
	public class MenuViewComponent : ViewComponent
	{
		private readonly IHttpContextAccessor _httpContextAccessor;
		private Sessao _sessao;
		private A6PerfilBusiness _perfilNegocio;
		private readonly IA6PerfilRepositorio _perfilRepositorio;
		public MenuViewComponent(IHttpContextAccessor httpContextAccessor, IA6PerfilRepositorio perfilRepositorio)
		{
			_httpContextAccessor = httpContextAccessor;
			_perfilRepositorio = perfilRepositorio;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			if (Sessao.ValidarExistirUsuarioSessao(_httpContextAccessor))
			{
				_sessao = new Sessao(_httpContextAccessor);
				_perfilNegocio = new A6PerfilBusiness(_perfilRepositorio);
				MenuViewModel menu = null;
				if (_sessao.UsuarioExterno != null) 
				{
					var perfisUsuarioExterno = _perfilNegocio.RetornarPerfisUsuarioExterno(_sessao.UsuarioExterno);
					menu = new MenuViewModel(perfisUsuarioExterno);
				}
				if (_sessao.UsuarioInterno != null) 
				{
					var perfisUsuarioInterno = _perfilNegocio.RetornarPerfisUsuarioInterno(_sessao.UsuarioInterno);
					menu = new MenuViewModel(perfisUsuarioInterno);
				}
				 
				return View(menu);
			}
			else
			{
				return View("Index", "Home");
			}
		}
	}
}

Solucao/TCC.GestaoSaude/TCC.GestaoSaude.View/Controllers/PainelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Newtonsoft.Json;
using TCC.GestaoSaude.Business;
using TCC.GestaoSaude.DataAccess.Interface;
using TCC.GestaoSaude.Models;
using TCC.GestaoSaude.View.Models;
using TCC.GestaoSaude.View.SessionCustom;

namespace TCC.GestaoSaude.View.Controllers
{
	public class PainelController : Controller
	{
		private readonly IHttpContextAccessor _httpContextAccessor;
		private readonly IA1UsuarioRepositorio _usuarioRepositorio;
		private readonly IA6PerfilRepositorio _perfilRepositorio;
		private readonly IA13ProfissionalRepositorio _profissionalRepositorio;
		private readonly IA2UsuarioInternoRepositorio _usuarioInternoRepositorio;
		private readonly IA29AtendimentoRepositorio _atendimentoRepositorio;
		private readonly IA9ProntuarioRepositorio _prontuarioRepositorio;
		private readonly IA10RegistroEvolucaoEnfermagemRepositorio _registroEvolucaoEnfermagemRepositorio;
		private readonly IRelHistoricoEvolucaoEnfermagemRepositorio _relHistoricoEvolucaoEnfermagemRepositorio;
		private readonly IEmailEnvio _emailEnvio;


		private Sessao _sessao;
		public PainelController(IHttpContextAccessor httpContextAccessor,
								IA1UsuarioRepositorio usuarioRepositorio,
								IA6PerfilRepositorio perfilRepositorio,
								IA13ProfissionalRepositorio profissionalRepositorio,
								IA2UsuarioInternoRepositorio usuarioInternoRepositorio,
								IA29AtendimentoRepositorio atendimentoRepositorio,
								IA9ProntuarioRepositorio prontuarioRepositorio,
								IA10RegistroEvolucaoEnfermagemRepositorio registroEvolucaoEnfermagemRepositorio,
								IRelHistoricoEvolucaoEnfermagemRepositorio relHistoricoEvolucaoEnfermagemRepositorio,
								IEmailEnvio emailEnvio)
		{
			_httpContextAccessor = httpContextAccessor;
			_usuarioRepositorio = usuarioRepositorio;
			_perfilRepositorio = perfilRepositorio;
			_profissionalRepositorio = profissionalRepositorio;
			_usuarioInternoRepositorio = usuarioInternoRepositorio;
			_atendimentoRepositorio = atendimentoRepositorio;
			_prontuarioRepositorio = prontuarioRepositorio;
			_registroEvolucaoEnfermagemRepositorio = registroEvolucaoEnfermagemRepositorio;
			_relHistoricoEvolucaoEnfermagemRepositorio = relHistoricoEvolucaoEnfermagemRepositorio;
			_emailEnvio = emailEnvio;
			_sessao = new Sessao(httpContextAccessor);

		}

		public IActionResult PaginaInicial()
		{	
			ViewBag.Session = _sessao;
			return View();
		}

		public IActionResult Logout()
		{
			_sessao.UsuarioExterno = null;
			_sessao.UsuarioInterno = null;
			return RedirectToAction("Index", "Home");
		}

		public IActionResult CadastrarNovoAtendimento()
		{
			ViewBag.Session = _sessao;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CadastrarNovoAtendimento(string formulario)
		{
			try
			{
				int indiceUnicoInformacaoUsuario = 0;
				string usuarioNaoExisteNoSistema = "0";

				UsuarioExternoViewModel usuario = JsonConvert.DeserializeObject<UsuarioExternoViewModel>(formulario);
				A29Atendimento atendimento = new A29Atendimento();
				A1Usuario usuarioCadastro = new A1Usuario();
				A29AtendimentoBusiness atendimentoNegocio = new A29AtendimentoBusiness(_atendimentoRepositorio, null, null, _usuarioRepositorio, _profissionalRepositorio, _usuarioInternoRepositorio);
				A1UsuarioBusiness usuarioNegocio = new A1UsuarioBusiness(_usuarioRepositorio, null, _perfilRepositorio, null);
				EmailBusiness emailNegocio = new EmailBusiness(_emailEnvio);

				if (usuario.UsuarioID != usuarioNaoExisteNoSistema)
				{
					var informacaoID = usuarioNegocio.BuscarUsuarioPorCPF(usuario.NumeroCPF).A3InformacaoCadastro.ToList()[indiceUnicoInformacaoUsuario].A3InformacaoCadastroId;
					atendimento.A3InformacaoCadastroId = informacaoID;
					atendimento.A29Data = DateTime.Now;
					atendimentoNegocio.CadastrarAtendimento(atendimento);
					if (atendimento.Mensagens.Count == 0)
					{
						return Json(new { NumeroAtendimento = atendimento.A29AtendimentoId, Mensagem = "" });
					}
					else
					{
						return Json(new { NumeroAtendimento = "0", Mensagem = atendimento.Mensagens[0].DescricaoMensagem });
					}
				}
				else
				{
					usuarioCadastro.A1UsuarioNumeroCpf = usuario.NumeroCPF;
					usuarioCadastro.A1UsuarioNome = usuario.NomeCompleto;
					usuarioCadastro.A1UsuarioSenha = "123456";

					A3InformacaoCadastro informacaoCadastro = new A3InformacaoCadastro();
					informacaoCadastro.A3InformacaoCadastroCelular = usuario.TelefoneCelular;
					informacaoCadastro.A3InformacaoCadastroDataNascimento = Convert.ToDateTime(usuario.DataNascimento);
					informacaoCadastro.A3InformacaoCadastroEmail = usuario.Email;
					informacaoCadastro.A3InformacaoCadastroNomeCompleto = usuario.NomeCompleto;
					informacaoCadastro.A3InformacaoCadastroNomeMae = usuario.NomeMae;
					informacaoCadastro.A3InformacaoCadastroNomePai = usuario.NomePai;
					informacaoCadastro.A3InformacaoCadastroNumeroCarteiraNacionalSaude = usuario.NumeroCarteiraSUS;
					informacaoCadastro.A3InformacaoCadastroTelefone = usuario.TelefoneResidencial;

					usuarioCadastro.A3InformacaoCadastro = new List<A3InformacaoCadastro>();
					usuarioCadastro.A3InformacaoCadastro.Add(informacaoCadastro);

					var loginCriado = usuarioNegocio.CriarLogin(usuarioCadastro);

					if (loginCriado)
					{
						atendimento.A29Data = DateTime.Now;
						atendimento.A3InformacaoCadastroId = usuarioCadastro.A3InformacaoCadastro.ToList()[indiceUnicoInformacaoUsuario].A3InformacaoCadastroId;
						atendimentoNegocio.CadastrarAtendimento(atendimento);
						if (atendimento.Mensagens.Count == 0)
						{
							EmailModel email = new EmailModel();
							email.Assunto = "Cadastro no sistema gestão de saúde";
							email.CorpoEmail = string.Format("Foi criado um cadastro no sistema de saude. <p>Usuario: {0}</p><p>Senha: {1} </p> ", usuarioCadastro.A1UsuarioNumeroCpf, usuarioCadastro.A1UsuarioSenha);
							email.DoEmail = "flavio.henriq@live.com";
							email.ParaEmail = "flavio.henriq@live.com";
							await emailNegocio.EnviarEmailAsync(email);

							return Json(new { NumeroAtendimento = atendimento.A29AtendimentoId, Mensagem = "", MensagemErro = "" });
						}
						else
						{
							return Json(new { NumeroAtendimento = "0", MensagemErro = "", Mensagem = atendimento.Mensagens[0].DescricaoMensagem });
						}
					}
					else
					{
						return Json(new { NumeroAtendimento = "0", MensagemErro = "", Mensagem = usuarioCadastro.Mensagens[0].DescricaoMensagem });
					}
				}
			}
			catch (Exception ex)
			{
				return Json(new { NumeroAtendimento = "0", Mensagem = "", MensagemErro = string.Format("Ocorreu um erro inesperado, contate seu administrador. Erro: {0}", ex.Message) });
			}
		}

		[HttpPost]
		public IActionResult PesquisarPorCPF(string numeroCPF)
		{
			try
			{
				A1UsuarioBusiness usuarioNegocio = new A1UsuarioBusiness(_usuarioRepositorio, _usuarioInternoRepositorio, _perfilRepositorio, _profissionalRepositorio);
				var usuarioPaciente = usuarioNegocio.BuscarUsuarioPorCPF(numeroCPF);

				if (usuarioPaciente.Mensagens.Count > 0)
				{
					return Json(new { Usuario = "", Mensagem = usuarioPaciente.Mensagens[0].DescricaoMensagem });
				}
				else
				{
					var jsonUsuario = JsonConvert.SerializeObject(usuarioPaciente, Formatting.Indented, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
					var usuarioDeserializado = JsonConvert.DeserializeObject<A1Usuario>(jsonUsuario);
					return Json(new { Usuario = usuarioDeserializado, Mensagem = "" });
				}
			}
			catch (Exception ex)
			{
				return Json(new { Usuario = "", Mensagem = ex.Message });
			}
		}

		public IActionResult PreencherProntuario()
		{
			ViewBag.Session = _sessao;
			return View();
		}

		[HttpPost]
		public IActionResult PesquisarPorCodigoAtendimento(string numeroAtendimento)
		{
			try
			{
				A29AtendimentoBusiness atendimentoNegocio = new A29AtendimentoBusiness(_atendimentoRepositorio, _prontuarioRepositorio, _registroEvolucaoEnfermagemRepositorio, _usuarioRepositorio, _profissionalRepositorio, _usuarioInternoRepositorio);
				var atendimento = atendimentoNegocio.BuscarAtendimento(Convert.ToInt32(numeroAtendimento));
				if (atendimento.Mensagens.Count == 0)
				{
					_sessao.IDAtendimento = atendimento.A29AtendimentoId;
					_sessao.RegistrosEvolucaoEnfermagem = null;
					string atendimentoJson = JsonConvert.SerializeObject(atendimento, Formatting.Indented, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
					var dados = JsonConvert.DeserializeObject<A29Atendimento>(atendimentoJson);
					List<RegistroEnfermagemViewModel> lstRegistroEnfermagemJaCadastrado = new List<RegistroEnfermagemViewModel>(); ;
					if (dados.RelAtendimentoProntuario.Count > 0)
					{
						var prontuario = dados.RelAtendimentoProntuario.ToList()[0].A9Prontuario;
						_sessao.IDProntuario = dados.RelAtendimentoProntuario.ToList()[0].A9Prontuario.A9ProntuarioId;
						foreach (var item in prontuario.RelHistoricoEvolucaoEnfermagem)
						{
							RegistroEnfermagemViewModel registro = new RegistroEnfermagemViewModel();
							registro.ID = item.A10RegistroEvolucaoEnfermagem.A10RegistroEvolucaoEnfermagemId;
							registro.Data = Convert.ToDateTime(item.A10RegistroEvolucaoEnfermagem.A10RegistroEvolucaoEnfermagemData).ToString("dd/MM/yyyy");
							registro.Hora = ((TimeSpan)item.A10RegistroEvolucaoEnfermagem.A10RegistroEvolucaoEnfermagemHora).ToString(@"hh\:mm\:ss");
							registro.Descricao = item.A10RegistroEvolucaoEnfermagem.A10RegistroEvolucaoEnfermagemDescrição;
							registro.Profissional = item.A10RegistroEvolucaoEnfermagem.A13ProfissionalCodigoCnsNavigation.A13ProfissionalNome;

Solucao/TCC.GestaoSaude/TCC.GestaoSaude.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TCC.GestaoSaude.View</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Matrix/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/css/Matrix/matrix-login.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-mask/jquery.mask.js"></script>
    <link href="~/css/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>

    @RenderBody()
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/matrix.login.js"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

Solucao/TCC.GestaoSaude/TCC.GestaoSaude.View/Views/Shared/_LayoutPainel.cshtml
@{
    var informacaoUsuario = TCC.GestaoSaude.View.SessionCustom.Sessao.RetornarInformacaoUsuario(ViewBag.Session);
    ViewBag.ItensMenu = ViewBag.Session.ItensMenu;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Gestão de Saúde</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="~/js/Matrix/jquery.min.js"></script>
    <script src="~/js/Notificacao/notifIt.js"></script>
    <script src="~/js/site.js"></script>
    <link href="~/css/Notificacao/notifIt.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Matrix/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Matrix/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/css/Matrix/fullcalendar.css" />
    <link rel="stylesheet" href="~/css/Matrix/matrix-style.css" />
    <link rel="stylesheet" href="~/css/Matrix/matrix-media.css" />
    <link href="~/css/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Matrix/jquery.gritter.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
    <!--Header-part-->
    <div id="header"> 
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Bem Vindo</span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="icon-user"></i> @informacaoUsuario.NomeUsuario</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> Perfis: @informacaoUsuario.Perfis</a></li>
                    <li class="divider"></li>
                    <li><a asp-action="Logout" asp-controller="Painel"><i class="icon-key"></i> Sair</a></li>
                </ul>
            </li>
            <li class=""><a title="" asp-action="Logout" asp-controller="Painel"><i class="icon icon-share-alt"></i> <span class="text">Sair</span></a></li>
        </ul>
    </div>
    <!--close-top-Header-menu-->
    <!--start-top-serch-->
    <div id="search">
        @*<input type="text" placeholder="Search here..." />
            <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>*@
    </div>
    <!--close-top-serch-->
    <!--sidebar-menu-->
    <div id="sidebar">
        <a asp-action="PaginaInicial" asp-controller="Painel" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
        <ul>
            @await Component.InvokeAsync("Menu")
        </ul>
    </div>
    <!--sidebar-menu-->
    <!--main-container-part-->
    <div id="content">
        @RenderBody()
    </div>
    <!--end-main-container-part-->
    <!--Footer-part-->
    <div class="row-fluid">
        <div id="footer" class="span12"> 2020 &copy; TCC - POS Engenharia de Software - PUC Minas</div>
    </div>
    <!--end-Footer-part-->



    <script src="~/js/Matrix/excanvas.min.js"></script>
    <script src="~/js/Matrix/jquery.ui.custom.js"></script>
    <script src="~/js/Matrix/bootstrap.min.js"></script>
    <script src="~/js/Matrix/jquery.flot.min.js"></script>
    <script src="~/js/Matrix/jquery.flot.resize.min.js"></script>
    <script src="~/js/Matrix/jquery.peity.min.js"></script>
    <script src="~/js/Matrix/fullcalendar.min.js"></script>
    <script src="~/js/Matrix/matrix.js"></script>
    <script src="~/js/Matrix/matrix.dashboard.js"></script>
    @*<script src="~/js/Matrix/jquery.gritter.min.js"></script>*@
    <script src="~/js/Matrix/matrix.interface.js"></script>
    <script src="~/js/Matrix/matrix.chat.js"></script>
    <script src="~/js/Matrix/jquery.validate.js"></script>
    <script src="~/js/Matrix/matrix.form_validation.js"></script>
    <script src="~/js/Matrix/jquery.wizard.js"></script>
    <script src="~/js/Matrix/jquery.uniform.js"></script>
    <script src="~/js/Matrix/select2.min.js"></script>
    <script src="~/js/Matrix/matrix.popover.js"></script>
    <script src="~/js/Matrix/jquery.dataTables.min.js"></script>
    <script src="~/js/Matrix/matrix.tables.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>